### ISSUE TITLE
erroneous #if __cplusplus

### ISSUE THREAD

**Issue by iluetkeb** [micro-ROS/rosidl_typesupport_microxrcedds#11]
in  rosidl_typesupport_microxrcedds/rosidl_typesupport_microxrcedds_c/resource/rosidl_typesupport_microxrcedds_c__visibility_control.h.in, the statement `#if __cplusplus` is used. 

This causes errors when *not* compiling with C++. It should read `#ifdef __cplusplus` instead. The dependent statements in the same file need to be adjusted as well.

**Comment by pablogs9** [comment]
Solved in https://github.com/micro-ROS/rosidl_typesupport_microxrcedds/pull/42
